### ISSUE TITLE
Station editor: Sampling period fields

### ISSUE THREAD

**Issue by tomlatter** [OceanOPS/sot-metadata#10]
**Describe the bug**
~~sampling period and total sampling perdiod : we can not enter ISO info. Suggest to have two fields a numeric one and alist with seconds/minutes/hours/days (or only seconds)~~
Not working in several cases. Info are not saved after 30s

**Additional context**
Reported by JB

**Comment by jbcohuet** [comment]
That's OK. If you can just change the legend which still refers to ISO format
![image](https://user-images.githubusercontent.com/103053433/167082283-0bd7d0c4-b721-4784-a119-6458a90d936a.png)

**Comment by tomlatter** [comment]
Seems to work now without issue
