### ISSUE TITLE
Call sign search in ship filed is not working. Try FKJB and enter

### ISSUE THREAD

**Issue by tomlatter** [OceanOPS/sot-metadata#14]
**Describe the bug**
Call sign search in ship filed is not working. Try FKJB and enter
The free text selection only searches by Name (should also filter by ICES/IMO/CALL SIGN).

**Additional context**
Reported by JB

**Comment by tomlatter** [comment]
Fixed, not yet published.

**Comment by jbcohuet** [comment]
Ok it is working thanks
