### ISSUE TITLE
SOT daily export

### ISSUE THREAD

**Issue by jbcohuet** [OceanOPS/sot-metadata#15]
We are tying to automatically process the new SOT export https://ocean-ops.org/share/sot/status/sot_all.csv for BUFR encoding. 
In the CSV, the comma is the separator for the main field but also for the sub-fileds like Parameter:MAKE_MODEL

AIRTEMP:ROTRONIC_MP101A,HUM:GENERIC_ELECTRONIC HYGROMETER,WD:RM YOUNG_05103,WS:RM YOUNG_05103,ATMPRESS:VAISALA_PTB210

Is it possible to switch to ';' instead of ',' for the main filed separator, or sub-filed separator ? That will help a lot. 

thanks
Jean-Baptiste

**Comment by anthoninlize** [comment]
If no objection, we will change the sub field separator to ';'. 

However, double quotes are present to distinguish contents from separators.

**Comment by jbcohuet** [comment]
That would be great
I think they are no objections yet as we are the first to use it :)
but it may have an impact for the upload format too, correct ?

note that ';' are already used for sub-field separator for the field NETWORK

**Comment by anthoninlize** [comment]
Indeed!
The upload function is flexible (would I dare saying 'smart'?) enough to detect those. To be tested and confirmed, but if not, we'll update it. This is not an issue.

Thanks for the note. We definitely need to use the same sub-field separator.

**Comment by jbcohuet** [comment]
Thanks. Looks all good.
