### ISSUE TITLE
Sampling period < 1second

### ISSUE THREAD

**Issue by jbcohuet** [OceanOPS/sot-metadata#16]
For windsensors, sampling period is usually 250 or 500ms.
that can't be entered (0.25 seconds is registerd as 0). Maybe add ms to the list of units.

**Comment by anthoninlize** [comment]
I think 0.25s should be handled as well. Actually it would be easier if later on we need to compare values... In both cases that would be feasible, but having only 's' makes it more straightforward.

**Comment by jbcohuet** [comment]
Anthonin, it is fine in my opinion if we can enter 0.25s but now we can't

![image](https://user-images.githubusercontent.com/103053433/167097379-71b4b5ef-9fcd-432a-b0c5-c577493de3a4.png)
After saving 
![image](https://user-images.githubusercontent.com/103053433/167097425-e0972ade-b6fc-46b6-89b0-c48c06ad2800.png)

**Comment by anthoninlize** [comment]
Yes agreed, this is a bug to fix

**Comment by tomlatter** [comment]
Fixed, not yet published

**Comment by jbcohuet** [comment]
ok good now
