### ISSUE TITLE
SOT export

### ISSUE THREAD

**Issue by jbcohuet** [OceanOPS/sot-metadata#2]
The ship names are not always present in the CSV export, full SOT format

![image](https://user-images.githubusercontent.com/103053433/165093664-d2b61273-7e4c-417f-9478-d86eae9afc67.png)

![image](https://user-images.githubusercontent.com/103053433/165093777-5c423774-0407-4c18-9e59-c7b28d46897f.png)

**Comment by jbcohuet** [comment]
yes French VOS fleet

**Comment by anthoninlize** [comment]
I have coherent results here...
Not logged in:
![image](https://user-images.githubusercontent.com/17119571/165309227-013d5ca8-0f78-4e84-9085-40111496b828.png)
Logged in:
![image](https://user-images.githubusercontent.com/17119571/165309380-16f30e59-454b-4324-bad9-e56c6f5477ab.png)

Would you mind trying again please and see if it's fixed ? Thanks

**Comment by jbcohuet** [comment]
Still the same


![image](https://user-images.githubusercontent.com/103053433/165310670-2906d2fe-416f-4929-b1c8-910d848d7c34.png)

**Comment by anthoninlize** [comment]
Thanks. @tomlatter can you follow up with tests please ?

**Comment by tomlatter** [comment]
Fixed, not yet published. Ship name shouldn't have been for non-admins on their fleets.

**Comment by jbcohuet** [comment]
Ok now as long as the ship are  in the system, which is not always the case for our CLOSED stations, but it is OK for the NOT CLOSED stations as the ships where entered manually when missing.
