### ISSUE TITLE
'Load saved query' windows not displaying correctly

### ISSUE THREAD

**Issue by emmasteventon** [OceanOPS/sot-metadata#22]
EDIT Anthonin: see 2nd comment

**Comment by emmasteventon** [comment]
When clicking on the button to load saved queries, the window that opens with the list has no option to scroll or to move or close the window:
![image](https://user-images.githubusercontent.com/103102833/167093794-c7e16e83-412d-4d02-88c0-60aab290adb5.png)

If you then click 'manage saved queries' it closes the list but you then lose the ability to see any of the menu's at the top of the screen and the only way to get out of this is to do a screen refresh:
![image](https://user-images.githubusercontent.com/103102833/167094127-ba960f03-6cc6-49bc-88de-7425bccb8cd2.png)

**Comment by tomlatter** [comment]
Fixed, not yet published
