### ISSUE TITLE
Inspect ship : station historial

### ISSUE THREAD

**Issue by jbcohuet** [OceanOPS/sot-metadata#23]
For that station, a GTS-ID was used and then the SOT-ID.
We have 3 lines, and the callsign was never used as GTS-ID

![image](https://user-images.githubusercontent.com/103053433/167094916-f5713958-65cd-47cc-9fea-54b19a3da80e.png)

**Comment by jbcohuet** [comment]
On this same ship, I don't see that there is a french ASAP station

**Comment by tomlatter** [comment]
> On this same ship, I don't see that there is a french ASAP station
Should there be a french ASAP station?
Regarding the extra row in the table with the call sign, it has been removed from the database.

**Comment by jbcohuet** [comment]
It is the station KJJF9XN, french station but in E-ASAP programme. 
but the ship seems to be masked when I inspect the station.
![image](https://user-images.githubusercontent.com/103053433/168735431-666b65d0-4356-4680-b2a0-f7e504428cae.png)

We also have ASAP station on CMA CGM Fort Fleur d'Epee, CMA CGM FORT Royal, CMA CGM Fort Satin Charles.
Probably masked also.

**Comment by anthoninlize** [comment]
It should not be an issue anymore, since we unmask all ships linked to VOS-FR and VOS-GB.

**Comment by jbcohuet** [comment]
Ok, that's fine now for CMA CGM FORT Royal, CMA CGM Fort Satin Charles
The problem  is that KJJF9XN is on the wrong ship. It should be CMA CGM FORT de France instead of CMA CGM fort St Pierre. The other ones are OK. 

And CMA CGM fleur d'EPEE / 2EERVTP is only ASAP at the moment (VOS soon), and still masked so I don't see them. 
![image](https://user-images.githubusercontent.com/103053433/169258685-fa7fbb34-3eba-4704-9592-116e0aa8a563.png)

**Comment by MKrieger29** [comment]
The station KJJF9XN  is now linked to the ship CMA CGM FORT de France. 
About the mask on the ships, I managed only the ships linked to VOS programs (for France & UK). Should I do the same thing for ASAP programs? Which ones?

**Comment by jbcohuet** [comment]
Thanks Magali
For ASAP, I would say yes but I think that @MartinOceanOPS  wanted to discuss with Rudolf about that. 

Even if ship is masked for whichever reason, I think that it would be good do know that there is a (ASAP/VOS) station onboard, without giving the SOT-ID, on the inspect ship windows.
Does that sound possible ?

**Comment by anthoninlize** [comment]
@jbcohuet I agree, I think we could list it without further details. But I wonder if we should spend time on this, if all SOT logged in users can see it without any restriction, and if masks usage is upon extinction... What do you think?

**Comment by jbcohuet** [comment]
Hi Anthonin, If every SOT logged user can see everything, in that case it is fine and the problem is solved.

**Comment by jbcohuet** [comment]
Did we agree on that behaviour or it is still under discussion ?

**Comment by anthoninlize** [comment]
I think we agreed on it.

@tomlatter can you confirm this feature is implemented or not yet? (all SOT linked users can see everything?)

**Comment by tomlatter** [comment]
I confirm this is implemented, logged in users linked to an SOT program or network can see all ships.

**Comment by jbcohuet** [comment]
perfect,
