### ISSUE TITLE
export of active stations only 

### ISSUE THREAD

**Issue by jbcohuet** [OceanOPS/sot-metadata#27]
Hi, 
Is it possible to have a export similar to https://ocean-ops.org/share/sot/status/sot_all.csv but only with active VOS stations.
That means that we will have a unique line per GTS-ID.
That will help to be sure to use the correct information for BUFR encoding. 

Thanks
Jean-Baptiste

**Comment by jbcohuet** [comment]
Hi all, 
As we are using that file for our internal developments on BUFR encoding, is there any possibilities to have that 'active' export in a short terms or we have to wait for Anthonin ? 
Thanks
 JB

**Comment by anthoninlize** [comment]
Hi JB, 

sorry for the late reply. It is possible, but since this will be a SOT file (and not VOS file), you will have in general one line per GTS-ID, but you might have several ones in some cases (eg, if GTS-ID shared between VOS station and ASAP).

**Comment by anthoninlize** [comment]
Done, to review:
https://www.ocean-ops.org/share/sot/status/sot_notclosed.csv

**Comment by jbcohuet** [comment]
Hi Anthonin, 

Thanks, That looks easier to use for us

Few remarks/request : 
- Do you see possible to have only VOS stations in that export ? 
- Is that possible to archive it here too : https://www.ocean-ops.org/share/sot/status/archives/. It would be easier to handle for our tool in charge of requesting the file everyday and pushing it to all our applications. 
- Even among the VOS I found ~70 duplicate GTS-ID. In that case we don't know which to use.  Maybe they are stations to merge. The list of duplicates is given below.
- Why some inactive stations do not have WIGOS-ID ?

Thanks
JB


Duplicated GTS-ID 
C6YM7
VRCS2
VRPY7
VRDK7
VRLA6
WARL
V7UT7
C6AT2
ONIS
C6BQ8
9V2727
9V9726
VRKQ7
VRMM1
VRNY5
KLBO
VRJZ9
C6BQ4
9V3913
V7YW4
GMHQL8E
V7VY7
ZGFY4
VRGG6
VRIZ5
V7IK7
3FKS5
VRNL8
VRYO9
3FMK7
VROH8
VRXL8
V7QJ5
MCMA3
C6YM5
C6AB9
WDJ4909
VRKX7
VROG7
VRZU4
VRCJ2
WDJ4009
7KHZ
VAAP
A8ZA9
S6NQ
VRIR7
KEBO
C6YM7
VRLT9
D5LJ2
3FFA5
V7HU7
9VHE2
A8ZA8
VROY7
VRLZ7
TBWUK90
C6BW3
VRDN6
OWDW2
9VMU5
VRLX5
V7QJ9
VRYO7
VRNE6
VRMS3
VRLL2
VRDU9
VRPY5
VRIF9
9V2907
7JZJ
VRGP2
