### ISSUE TITLE
New Version Number of TURBOWIN+ AUTO, TURBOWIN+ MANUAL and Turbowin+

### ISSUE THREAD

**Issue by mhoigt** [OceanOPS/sot-metadata#37]
### Description of the desired feature

pls make for VERSION_NUMBER_MAIN_DEVICE (TURBOWIN+ AUTO, TURBOWIN+ MANUAL) new version number 4.3 and 4.4 under ANCILLARY_DEVICE_VERSION (Turbowin+) new Versions Numbers, 4.2, 4.3 and 4.4

**Comment by MKrieger29** [comment]
Main model device TURBOWIN+ AUTO and TURBOWIN+ MANUAL => new versions 4.3 and 4.4
Ancillary device version TURBOWIN+ => new versions 4.2, 4.3 and 4.4
