### ISSUE TITLE
New Version number for EUCAWS/NEPTUNE

### ISSUE THREAD

**Issue by mhoigt** [OceanOPS/sot-metadata#38]
### Description of the desired feature

pls make for VERSION_NUMBER_MAIN_DEVICE (EUCAWS/NEPTUNE) new version number 0.4.4

**Comment by MKrieger29** [comment]
The version number 0.4.4 is added for the Main model device EUCAWS/NEPTUNE: 
![image](https://user-images.githubusercontent.com/74649916/221534275-34b948c7-1ad8-428a-937d-9e8422e0142b.png)
