### ISSUE TITLE
Update tables

### ISSUE THREAD

**Issue by jbcohuet** [OceanOPS/sot-metadata#40]
### Description of the desired feature

Could you update the table 2.12-2.17-MODEL_DEVICE.csv with
- Add Mini-Eucaws/WSM200 , 1.0.2;1.0.5 , VOS, AUTO , STERELA
- Edit Mercury, add 0.7.4 in software versions

For the ancillary device models, there is no table if I'm correct. 
For Eucaws/Neptune, Turbowin+ is the ancillary model, please add 4.4 in the ancillary device version

thanks
JB

**Comment by MKrieger29** [comment]
The ancillary device model information is in the 2.12-2.17-MODEL_DEVICE.csv reference table. You have to scroll to the right to see all the content of the table.

**Comment by MKrieger29** [comment]
The models and versions are added to the reference table in OceanOPS
