### ISSUE TITLE
Update AMOS2X Main device version number

### ISSUE THREAD

**Issue by AdamRyanMO** [OceanOPS/sot-metadata#41]
### Description of the desired feature

For the AMOS2x when updating the station info there is only the option to select main device version numbers 2.16 and 3.7 
Can you please create version 4.0 as an option? 

Thanks. 

### Suggested solution

I want the option to select version 4.0 under "main device version numbers"

**Comment by MKrieger29** [comment]
The version 4.0 can now be selected for the AMOS2x main device model has  new version 4.0 (in addition to 2.16 and 3.7 versions)
