### ISSUE TITLE
Add TW+ 4.5

### ISSUE THREAD

**Issue by mhoigt** [OceanOPS/sot-metadata#44]
### Description of the desired feature

pls make for VERSION_NUMBER_MAIN_DEVICE (TURBOWIN+ AUTO, TURBOWIN+ MANUAL) new version number 4.5 under ANCILLARY_DEVICE_VERSION (Turbowin+) new Versions Number, 4.5

4.5 will be released soon, please add it to the list so that you can work with it quickly.

**Comment by MKrieger29** [comment]
I added this new version as described in the issue
(see [here](https://github.com/OceanOPS/sot-metadata/blob/main/tables/2.12-2.17-MODEL_DEVICE.csv))
