### ISSUE TITLE
Ship editor window hides behind other windows

### ISSUE THREAD

**Issue by tomlatter** [OceanOPS/sot-metadata#7]
**Describe the bug**
Henry: NOK Wehn uploading metadata and ship is unknown, it cannot be registered as according window hides behind all others and cannot be brought to front without closing all other windws, by that loosing e.g. all uploaded metadata.

**Additional context**
Reported by HK

**Comment by tomlatter** [comment]
A new version of ship editor module is published, doesn't hide behind other windows

**Comment by jbcohuet** [comment]
Tested, OK
